### ISSUE TITLE
Massive lag on certain planets

### ISSUE THREAD

**Issue by SonicSpeedster16** [alphawolf918/Zollern-Galaxy#1]
Hello,

I am really wanting to add this mod to my modpack, but while testing it out I ran into some very severe lag issues on the following two planets: Zollus and Kriffon. Any time I would go to one of those planets, the TPS on my single player world would instantly drop to around 3. leaving the planet and returning to a different planet would allow the TPS to return to 20. I did not have this issue when visiting Eden or Purgot.

Minecraft 1.12.2
Forge 2847
Galacticraft 238, Zollern Galaxy 2.0.8 (also have the latest versions of Extra Planets and More Planets as well).

Please let me know if I can provide any additional information.

**Comment by alphawolf918** [comment]
Hey, thanks for bringing this to my attention! I'll check this out when I get back into working on it. I'm glad you brought this up because it is actually something I was wondering about. I'll see what I can do about reducing the memory load from those worlds. Zollus isn't as heavily intensive as Kriffon is, so I'll start on the latter first. I think I know what's going on with both, though.

I'd imagine Candora is pretty laggy too, right? I'm asking because I'm curious and will be extremely surprised if it isn't.

**Comment by SonicSpeedster16** [comment]
Sounds good I look forward to it!

I did not check all the planets, and Candora is one that I didn't. I can give that one a test in the next few days though and see if it suffers the same lag.

**Comment by alphawolf918** [comment]
It's arguably the laggiest of them all, it seems like. But yeah I'll see what I can do, regardless. Thank you.

**Comment by alphawolf918** [comment]
How is the new version holding up with this? I plan to make more changes, but I'm curious where things are right now.

**Comment by SonicSpeedster16** [comment]
@alphawolf918 sorry I did not see your new comment until now (not sure why I did not get a notification). I'll be sure to give the latest version a test (though it may not be until this coming weekend) and will let you know. Appreciate your work on this!

**Comment by SonicSpeedster16** [comment]
Did a short test of this today. Candora is MUCH improved and I am getting a stable 20TPS now! Still getting massive TPS drops on Zollus and Kriffon though.

**Comment by alphawolf918** [comment]
Alright, I'll give it another look-over when I have some time. Thank you!

**Comment by alphawolf918** [comment]
Hey, just letting you know that I am still working this. The latest release should reduce the lag a little bit (you may need to delete the kriffus and zollus folders under your planets folder), but I'm working on a more permanent fix soon.

**Comment by SonicSpeedster16** [comment]
Awesome, sounds good I look forward to testing it!

**Comment by alphawolf918** [comment]
Reworked Zollus and Kriffon entirely; they should be better now. Closing this as solved but if you still have issues then please let me know. Thank you.
