### ISSUE TITLE
[CRASH] Parachest Rendering Crash

### ISSUE THREAD

**Issue by reverentfeynmen** [alphawolf918/Zollern-Galaxy#100]
**Describe the bug**
A clear and concise description of what the bug is. Please also tell us if you were playing single player, or on a server, as behaviors tend to differ, depending.

**Expected behavior**
A clear and concise description of what you expected to happen. Create a Space Station.

**Screenshots**
Please provide screenshots to help explain your problem.

**Minecraft and PC Information (please complete the following information):**
 - Minecraft Version: [e.g. 1.12.2]
 - Mod Version [e.g. 2.0.33]
 - RAM Allocated [e.g. 8 GB]

**Additional context**
Add any other context about the issue here, if needed. ---- Minecraft Crash Report ----

WARNING: coremods are present:
  MicdoodlePlugin (Galacticraft-1.12.2-4.0.6.jar)
Contact their authors BEFORE contacting forge

// Hey, that tickles! Hehehe!

Time: 5/16/24 4:18 PM
Description: Ticking entity

java.lang.ClassCastException: micdoodle8.mods.galacticraft.core.entities.EntityParachest cannot be cast to net.minecraft.entity.EntityLivingBase
	at zollerngalaxy.blocks.ZGBlockBase.func_176199_a(ZGBlockBase.java:146)
	at net.minecraft.entity.Entity.func_70091_d(Entity.java:928)
	at micdoodle8.mods.galacticraft.core.entities.EntityParachest.func_70071_h_(EntityParachest.java:159)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at zollerngalaxy.blocks.ZGBlockBase.func_176199_a(ZGBlockBase.java:146)
	at net.minecraft.entity.Entity.func_70091_d(Entity.java:928)
	at micdoodle8.mods.galacticraft.core.entities.EntityParachest.func_70071_h_(EntityParachest.java:159)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)

-- Entity being ticked --
Details:
	Entity Type: galacticraftcore:para_chest (micdoodle8.mods.galacticraft.core.entities.EntityParachest)
	Entity ID: 41227
	Entity Name: Parachest
	Entity's Exact location: -8.50, 63.00, -1.50
	Entity's Block location: World: (-9,63,-2), Chunk: (at 7,3,14 in -1,-1; contains blocks -16,0,-16 to -1,255,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: New World
	All players: 1 total; [GCEntityPlayerMP['SR8TLine'/0, l='New World', x=0.50, y=65.00, z=0.50]]
	Chunk stats: ServerChunkCache: 2809 Drop: 0
	Level seed: 5143000473552388068
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1253906480 bytes (1195 MB) / 2589982720 bytes (2470 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m
	IntCache: cache: 0, tcache: 0, allocated: 1, tallocated: 14
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 16 mods loaded, 16 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                  | Version      | Source                               | Signature                                |
	|:------ |:------------------- |:------------ |:------------------------------------ |:---------------------------------------- |
	| LCHIJA | minecraft           | 1.12.2       | minecraft.jar                        | None                                     |
	| LCHIJA | mcp                 | 9.42         | minecraft.jar                        | None                                     |
	| LCHIJA | FML                 | 8.0.99.99    | forge-1.12.2-14.23.5.2860.jar        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge               | 14.23.5.2860 | forge-1.12.2-14.23.5.2860.jar        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | micdoodlecore       | 4.0.6        | minecraft.jar                        | None                                     |
	| LCHIJA | galacticraftcore    | 4.0.6        | Galacticraft-1.12.2-4.0.6.jar        | None                                     |
	| LCHIJA | galacticraftplanets | 4.0.6        | Galacticraft-1.12.2-4.0.6.jar        | None                                     |
	| LCHIJA | asmodeuscore        | 1.0.1        | AsmodeusCore-1.12.2-1.0.1.jar        | None                                     |
	| LCHIJA | crafttweaker        | 4.1.20       | CraftTweaker2-1.12-4.1.20.698.jar    | None                                     |
	| LCHIJA | ctgui               | 1.0.0        | CraftTweaker2-1.12-4.1.20.698.jar    | None                                     |
	| LCHIJA | jei                 | 4.16.1.301   | jei_1.12.2-4.16.1.301.jar            | None                                     |
	| LCHIJA | crafttweakerjei     | 2.0.3        | CraftTweaker2-1.12-4.1.20.698.jar    | None                                     |
	| LCHIJA | galacticrafttweaker | 1.12.2-1.0.3 | GalacticraftTweaker-1.12.2-1.0.3.jar | b02331787272ec3515ebe63ecdeea0d746653468 |
	| LCHIJA | spaceambient        | 0.0.1        | SpaceAmbient-1.12.2-0.0.1.jar        | None                                     |
	| LCHIJA | spacex              | 1.12.2       | SpaceCraftX-1.2.1.jar                | fdf52b4949f62c459bc7c8b88b3fc626710d49ff |
	| LCHIJA | zollerngalaxy       | 2.0.45       | ZollernGalaxy-1.12.2-2.0.45.jar      | None                                     |

	Loaded coremods (and transformers): 
MicdoodlePlugin (Galacticraft-1.12.2-4.0.6.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [GCEntityPlayerMP['SR8TLine'/0, l='New World', x=0.50, y=65.00, z=0.50]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by alphawolf918** [comment]
Wrong Galacticraft Core version. To use this mod, you'll need to downgrade your Galacticraft version to 4.0.2. I do not have any plans to upgrade the mod currently. I have real life stuff going on. The mod is not considered dead or abandoned but on a continued hold. Issues may or may not be addressed when work is resumed.
