### ISSUE TITLE
Repost request and Description

### ISSUE THREAD

**Issue by EndsM** [alphawolf918/Zollern-Galaxy#13]
[mcbbs.net](url)
MCBBS is a minecraft forum in china.
It contains quantity of contents about Minecraft. Mods is a main part of it's contents.
Developers in china will mainly post there mods for JAVA edition to it. And a lot of people will post mods around world at the premiss of got the permition from author.
I can't explain it clearly, just like I can't explain the minecraftforum's community. But in a short word: it is the main minecraft community in china.
here is the Draft of my post in MCBBS. It still in my Draft box.
https://s1.ax1x.com/2020/03/16/88XWbd.png
https://s1.ax1x.com/2020/03/16/88XcvD.png
https://s1.ax1x.com/2020/03/16/88XRDH.png
https://s1.ax1x.com/2020/03/16/88XhVA.png
I will not post it without your permit

**Comment by alphawolf918** [comment]
As long as you do not upload the file, and simply use a link to it instead, you may post it. Otherwise, no.
