### ISSUE TITLE
Crash bug with the latest version of the mod

### ISSUE THREAD

**Issue by HDL34** [alphawolf918/Zollern-Galaxy#22]
I attach the crash log to you to see why the game crashes with the last 2 versions while version 2.0.12 works.
[debug.log](https://github.com/alphawolf918/Zollern-Galaxy/files/4547654/debug.log)
[latest.log](https://github.com/alphawolf918/Zollern-Galaxy/files/4547655/latest.log)
[crash-2020-04-28_19.53.21-server.txt](https://github.com/alphawolf918/Zollern-Galaxy/files/4547656/crash-2020-04-28_19.53.21-server.txt)

**Comment by alphawolf918** [comment]
User was advised previously that it was likely a compatibility issue. Crash log confirms this, as well as a lack of RAM. Issue cannot be reproduced. Closing ticket.
