### ISSUE TITLE
Zollerngalaxy is trying to generate chunks with an biome.altum. its repeating it and trying to force it it

### ISSUE THREAD

**Issue by galacticrafthuman** [alphawolf918/Zollern-Galaxy#25]
Zollerngalaxy is trying to generate chunks with an biome.altum. its repeating it and trying to force it it, it happened when i was on galacticraft mars

**Comment by DabbingEevee** [comment]
can you try to send a log?

**Comment by alphawolf918** [comment]
Is this still an issue? Need a log to determine what's actually happening. Will close ticket if no feedback from user by tomorrow.

**Comment by alphawolf918** [comment]
No response from user. Closing ticket.
