### ISSUE TITLE
2.0.18 says it's an invalid version

### ISSUE THREAD

**Issue by BrisingrAerowing** [alphawolf918/Zollern-Galaxy#31]
I downloaded the update through the Twitch launcher, and get an invalid version error in chat on world load.

**Comment by alphawolf918** [comment]
Whoops, forgot to unset that in the code. Sorry about that! The version is valid, but I put that in there for debug purposes so it's not used when it shouldn't be. Will get that fixed ASAP. Thanks bunches.

**Comment by alphawolf918** [comment]
Alright, new version here -

https://www.curseforge.com/minecraft/mc-mods/zollern-galaxy/files/3054957

Thanks for letting me know!!
