### ISSUE TITLE
[Suggestion] TCon material blacklist

### ISSUE THREAD

**Issue by BlueCreeper160** [alphawolf918/Zollern-Galaxy#32]
Some TCon addons register materials that Zollern Galaxy already registered, for example radium with More TCon, causing a game crash, to avoid this I suggest a blacklist in the config file, where you can write the material to not register on TCon. (Sorry for my bad english)

**Comment by alphawolf918** [comment]
I'll look into configurable materials and traits. Thanks for letting me know. Fun fact: the author of that mod has been a large contributor to this one and I work with him closely.

**Comment by DabbingEevee** [comment]
yup, i am also working on a material blacklist. if all goes well, you should be able to manually select which materials to use form either mod

**Comment by alphawolf918** [comment]
Alrighty, issue has been fixed (in both of our mods) on our dev side. There's a few more things I'd like to do before I do a full release, but your fix is in there in both mods. Thanks for letting us know!

**Comment by alphawolf918** [comment]
Issue should be fixed.
