### ISSUE TITLE
Exception in server tick loop

### ISSUE THREAD

**Issue by xDawnshadow** [alphawolf918/Zollern-Galaxy#49]
Good Evening Sir,

While setting up a Server I've run into a small Problem which resulted in an Exception in server tick loop crash
[crash-2021-02-22_23.22.19-server.txt](https://github.com/alphawolf918/Zollern-Galaxy/files/6025597/crash-2021-02-22_23.22.19-server.txt)

I hope this is the Right place where I may ask for help -> Really appreciate any help I receive:)
Stay safe and take care in these times everybody

**Comment by DabbingEevee** [comment]
it seems like an error on our side. what did you do to trigger this error?

**Comment by alphawolf918** [comment]
Good evening! Thanks for bringing this to our attention. This is actually very helpful and answers a question I had. I can't work on this tonight, but I should be able to get to it this week hopefully.

I think I know what happened here, DE. Seems me using EntitySP was - duh - bad. I thought that would only run client side with the way I had it setup, but clearly I missed something. It's fixable, just might be a bit. Thank you for responding so promptly though man.

**Comment by alphawolf918** [comment]
Found the problem and wow I feel like a doof. I'll try to get this fixed tomorrow. Thanks again.

**Comment by alphawolf918** [comment]
Got the fix ready to go, as soon as my desktop PC decides to behave and connect to the Internet I can release it. Right now I'm on my laptop with no way of getting it between the two without a huge headache. If it keeps up then the update may have to wait, but I thought I'd let you know that I do at least have it fixed.

**Comment by alphawolf918** [comment]
Link to bug fix: https://www.curseforge.com/minecraft/mc-mods/zollern-galaxy/files/3214857

May need to wait for the file to be approved.

Thanks for letting us know. Open this issue back up if it happens again.

**Comment by xDawnshadow** [comment]
Well well well, let's get back haha! Thanks for the fast answers as well! But well, here 

[crash-2021-02-24_10.01.25-server .txt](https://github.com/alphawolf918/Zollern-Galaxy/files/6034750/crash-2021-02-24_10.01.25-server.txt)

I didn't expect such a rapid answer, that's why I couldn't check this Conversation then

**Comment by alphawolf918** [comment]
No worries! I try to get to these as soon as I can, but sometimes that can take a while too. Yeah this issue cropped back up again, but see https://github.com/alphawolf918/Zollern-Galaxy/issues/50 for the current status. Thanks for the feedback.
