### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by bigenergy** [alphawolf918/Zollern-Galaxy#50]
ZollernGalaxy-1.12.2-v2.0.25
Server-side crash on start
https://pastebin.com/KbwUr0ty

**Comment by DabbingEevee** [comment]
not sure whats going on there, can you try a plain installation with only galacticraft and zollern galaxy?

**Comment by bigenergy** [comment]
> not sure whats going on there, can you try a plain installation with only galacticraft and zollern galaxy?

client method is executed on the server side
https://github.com/alphawolf918/Zollern-Galaxy/issues/50#issuecomment-784664426

**Comment by DabbingEevee** [comment]
thanks you for the fast reply and solution. ill get a pull request up as soon as possible.

**Comment by bigenergy** [comment]
another.. https://pastebin.com/VPnQ1iyz

**Comment by alphawolf918** [comment]
I'm aware of these issues, and will fix them when I have the time. Right now I haven't gotten to the first one. I appreciate the input and support, but I'm gonna need you to be patient please.

**Comment by alphawolf918** [comment]
This should fix it finally, I'm 99% sure. I released a new version with the fix on my GitHub Releases page, but I've also got one awaiting approval on CurseForge; preference is up to you, they're the same file.

Gonna close this, but please open it back up if this same issue occurs again. If it's a different issue, please make a new one. Thanks again.
