### ISSUE TITLE
Not taking thermal damage with Zollern Galaxy installed.

### ISSUE THREAD

**Issue by WT000** [alphawolf918/Zollern-Galaxy#54]
I don't seem to be taking thermal damage with this mod installed. To test this, I've only got the following mods installed:

GalacticraftCore (4.0.2.280)
GalacticraftPlanets
MicdoodleCore
ZollernGalaxy (2.0.26)

For instance, the damage and nausea effect are still happening on Venus, but my hearts don't lower.

![zollernbug](https://user-images.githubusercontent.com/55751558/114186505-da095980-993e-11eb-8f55-68c1b4b8a9ac.PNG)

Altum is also crashing my game, the crash report seems identical to wdadwda23's on the CurseForge page (though I've strangely now got it working? God knows what caused that xd).
ANoThEr eDiT, but I figured out that either Aether Legacy, Aether Continuation or Aether: Lost Content were causing the Altum crash.

**Comment by WT000** [comment]
Stangely looks like the Aether isn't causing the crash in a multiplayer server though, don't know what could be causing that.

**Comment by alphawolf918** [comment]
Huh, how strange. That's really weird, last time it was that people were taking too much thermal damage. Is this on every planet or just Venus? What about mine specifically?

As for the Altum crash, yeah that's an ongoing thing that I'm looking into. I honestly don't know what's doing that because in my mind it makes no sense and I can't reproduce it for some reason.

These are things that I'll be looking into though, thanks for letting me know.

**Comment by WT000** [comment]
I've tested it on a few planets / moons, here's the results:

Mars - No damage
Venus - No damage
Jupiter (Extra Planets) - No damage
Kriffon - No damage 

Oddly enough, I'm not seeing the oxygen / thermal menu in the top right when I'm on your planets as well.

**Comment by DabbingEevee** [comment]
can u try to reset your configs? that might be causing the issue

**Comment by WT000** [comment]
I reset all the configs and tried it with just Galacticraft and Zollern again, I'm getting the same issue.

![zollernbug](https://user-images.githubusercontent.com/55751558/114324028-ea2c5f00-9b1f-11eb-9584-88217ce03f9c.PNG)

**Comment by alphawolf918** [comment]
It's something I'll keep a lookout for, definitely the first time I heard of it, but I think I know why.
