### ISSUE TITLE
Minor Spelling Issue outputs Error to the log

### ISSUE THREAD

**Issue by TheComputerizer** [alphawolf918/Zollern-Galaxy#55]
When starting up my pack, I get this error in the log
```
Parsing error loading recipe zollerngalaxy:storm _amulet
com.google.gson.JsonSyntaxException: Unknown item 'zollerngalaxy:storm _amulet'
```
and I believe 'zollerngalaxy:storm _amulet' has an extra space so it should be 'zollerngalaxy:storm_amulet'?

**Comment by alphawolf918** [comment]
Yeah that's just leftover .lang stuff that I never got around to fixing because there wasn't any negative impact towards production; it's just log-spam. I need to clear off the JSON files; I'll get around to that. Thanks for letting me know.
