### ISSUE TITLE
Way too many alien villagers spawning

### ISSUE THREAD

**Issue by TheComputerizer** [alphawolf918/Zollern-Galaxy#59]
I am not sure what exactly happened here, but I was chilling in caligro making quests for [my pack](https://www.curseforge.com/minecraft/modpacks/dimensionhopper) and [this](https://imgur.com/a/ppxWkCd) happened. When I finally paused my quest making to run a /killall it killed about 4000 entities, which I am assuming means the spawn cap broke for some reason

**Comment by TheComputerizer** [comment]
This was for the most recent version 1.12.2-v2.0.28 on forge 14.23.5.2855

**Comment by alphawolf918** [comment]
Holy cow!!

Okay, I think there should be an option in the configs to turn off the Alien Villager passive spawn. That way they only spawn in the villages. I'll look into their spawn rate as well, but until then, could you give that a go for me please?

**Comment by alphawolf918** [comment]
This should be fixed now, please make another issue ticket if it isn't. Thanks again.
