### ISSUE TITLE
Language file issues

### ISSUE THREAD

**Issue by EndsM** [alphawolf918/Zollern-Galaxy#6]
As new version came out, I entered the game at once. However, the translation doesn't work at the first time.
So I tried to check the new version's translation an origin English file. But it doesn't changed any old lables, so even my translation don't include some new items, it should work for old items.
But it doesn't occured any chinese litter anyway. So I tried change the language file's name from "zh_CN.lang" into "zh_cn.lang" and then it worked.
I still not sure what happened, But can you check this and find out what caused it? Is the file's name or other problem? I'm not sure if it happened on KR too, But if it was the upcase caused it, it would happened on Korean too.
Thank you again for updata.

**Comment by alphawolf918** [comment]
You're right - it should be lowercase. Thank you for bringing this to my attention. I'm fixing it now.

**Comment by alphawolf918** [comment]
This has been fixed and will be in the next release in just a little while.
