### ISSUE TITLE
Dont work with wild nature

### ISSUE THREAD

**Issue by Sp3rick** [alphawolf918/Zollern-Galaxy#61]
Zollern 1.12.2 with WildNature latest version don't work togheter

edit: i have tried to change every Zollern id in the configuration but not work anyway, so i think it isn't a id problem

**Comment by alphawolf918** [comment]
Doesn't work how? I'm gonna need more information, sorry.

**Comment by alphawolf918** [comment]
This is an issue with that mod specifically, as the 1.12 version of it is in beta still, this would have to be addressed from their end, especially considering that this has nothing to do with the exploration of space, and Zollern Galaxy does not modify overworld generation.
