### ISSUE TITLE
Xathius Issues or Noticeables

### ISSUE THREAD

**Issue by xDawnshadow** [alphawolf918/Zollern-Galaxy#68]
- high Spawn rate of mobs
- villagers spawning randomly as well as in Vortex
- yellow buildings/safety pods are not correctly placed
- normal vanilla mine shafts, unknown if intended

**Comment by alphawolf918** [comment]
Mob spawn rate can certainly be lowered, yeah. Villagers are supposed to spawn randomly (by default), which can be disabled in the config, but they certainly are spawning way too often. I might make their spawn rate a config option as well. The yellow buildings you refer to are called Outposts, and yeah they're kinda wonky. For one, they're not supposed to generate in ocean-like biomes (e.g. where the lakes are Chargium, Fueltonium, Lava, Water, etc.), and that one's already on my Trello as a to-do thing. Normal vanilla mineshafts are intended, yes. I haven't tried my luck at custom ones yet, might not. I know it looks a little weird, though.

Thanks for your report. I'll leave it open until I get most of it squared away. :)
