### ISSUE TITLE
Temperature Not Working Right

### ISSUE THREAD

**Issue by Kydhead** [alphawolf918/Zollern-Galaxy#69]
So I read the change log that said how the celsius thing is fixed and I will say I don't think it is entirely fixed. For anyone wondering, the equation that converts F to C is C=(F-32)*(5/9) but when I plugged in the F value in, the C value that came out is different then the C value displayed on the HUD screen. So please fix that issue soon, most of my friends use C and it will be very confusing for them when they see -70C on a perfectly habitable and nice planet.

**Comment by alphawolf918** [comment]
Please provide screenshots, as when tested, everything worked fine. Show the F value as well as the C value, in two different screenshots. No fixes will be attempted any time soon.

**Comment by alphawolf918** [comment]
User could not provide screenshots in time, and verified that the formula works just fine. Closing.
