### ISSUE TITLE
Extra Utilities AngelRing bug

### ISSUE THREAD

**Issue by Sketc96** [alphawolf918/Zollern-Galaxy#71]
If I install ZollernGalaxy in my modpack, Angelring stop working
Double spacebar does not work to fly with the ring.
If I remove ZollernGalaxy it's all ok

Versions:
ZollernGalaxy 1.12.2-v2.0.34
Extra Utilities 1.12-1.9.9

**Comment by alphawolf918** [comment]
Hi there! Thanks for bringing this to my attention.

I'll have to add an option to the config to disable the custom flying, as one of my armor sets can interfere with it. I will look into that for the next update. Thanks again and I'll let you know when I get it done.

**Comment by alphawolf918** [comment]
Hey, could you do me a favor? I was going through my configs and saw this:

```
    # Toggle whether a full set of Radiance armor allows the Player to fly in Survival. Set to false to disable if this causes mod conflicts, compromises the safety of your server, or if you just hate fun. (default: true)
    B:"Enable Radiance Flying In Survival"=true
```
Could you try setting that to false and see what happens please?

**Comment by Sketc96** [comment]
Solved!
Thank u so much!

**Comment by alphawolf918** [comment]
Not a problem, happy to help.
