### ISSUE TITLE
Astros ice xray

### ISSUE THREAD

**Issue by mMONTAGEe** [alphawolf918/Zollern-Galaxy#81]
**Describe the bug**
Landing on Astros, approaching the ice, and seeing cave systems on the moon through ice,

**Expected behavior**
Unable to see through the ice, which also impacts the perfomance

**Screenshots**
https://cdn.discordapp.com/attachments/737202405959139350/944872730115866644/unknown.png
https://cdn.discordapp.com/attachments/737202405959139350/944872974199185408/unknown.png

**Minecraft and PC Information (please complete the following information):**
 - Minecraft Version: 1.12.2
  - Mod Version: 2.0.38
 - RAM Allocated: 5GB

**Additional context**
Zollern Galaxy might eating good chunk of RAM (need verification, didn't check in details)

**Comment by mMONTAGEe** [comment]
Also dropped blocks on Astros appear semitransparent

**Comment by alphawolf918** [comment]
The ice will be fixed in the next version.
