### ISSUE TITLE
Crash with wrong ID

### ISSUE THREAD

**Issue by magcicada** [alphawolf918/Zollern-Galaxy#83]
The dim ID of planet Kronos will cause crash with any ID.
this is the error in the log:[paste](https://pastebin.com/F62dJnMd)
I try to change many ID but it still crash.

**Comment by alphawolf918** [comment]
Found the problem and fixed it. Once the file is approved, you can reach the fixed version here:

https://www.curseforge.com/minecraft/mc-mods/zollern-galaxy/files/3657201
