### ISSUE TITLE
[Server] [2.0.41] Startup crash : Maveth World Provider overrides renderSky() Method on server side

### ISSUE THREAD

**Issue by TigerWalts** [alphawolf918/Zollern-Galaxy#87]
**Describe the bug**
The `WorldProviderMaveth` class overrides the `renderSky()` base method on server side. This results in Galacticraft trying to load the `SkyProviderMaveth` class which is client side only.

This causes a crash during start up:

> java.lang.NoClassDefFoundError: zollerngalaxy/core/dimensions/skyproviders/SkyProviderMaveth

**Additional context**

The `WorldProviderMaveth` needs to set the following method to client only:

https://github.com/alphawolf918/Zollern-Galaxy/blob/6ec50200c3b4cc6bf90b6f1adb51854eb7f0e4dd/src/main/java/zollerngalaxy/core/dimensions/worldproviders/WorldProviderMaveth.java#L172-L175

It looks like it's missing the `@SideOnly(Side.CLIENT)` decorator.

```java
	@Override
	@SideOnly(Side.CLIENT)
	protected void renderSky() {
		this.setSkyRenderer(new SkyProviderMaveth(this));
	}
```

`WorldProviderMaveth` also needs the `@SideOnly(Side.CLIENT)` decorator added to `getFogColor()` as `getStarBrightness()` is client only:

```java
	@Override
	@SideOnly(Side.CLIENT)
	public Vector3 getFogColor() {
		float f = 1.2F - this.getStarBrightness(1.0F);
		return new Vector3(1F / 255F * f, 1F / 255F * f, 24F / 255F * f);
	}
```

**Comment by alphawolf918** [comment]
Whoops, forgot to put that, thanks. Appreciate the detail you put in as well. Will get this fixed and uploaded soon.

**Comment by alphawolf918** [comment]
https://www.curseforge.com/minecraft/mc-mods/zollern-galaxy/files/3680055

Should be good now. Check latest release. If not, I'll take another look tomorrow, but I'm confident this will work.

**Comment by TigerWalts** [comment]
Server starts now. Thanks.
