### ISSUE TITLE
Living Entity cast not checked in ZGBlockBase class

### ISSUE THREAD

**Issue by TheComputerizer** [alphawolf918/Zollern-Galaxy#94]
**Describe the bug**
If an entity that is not a living entity triggers the `onEntityWalk` method in the `ZGBlockBase` class it will thrown a ClassCastException. [This line](https://github.com/alphawolf918/Zollern-Galaxy/blob/e277ebc0dd0c1f09122368b6733f7e6b30d78451/src/main/java/zollerngalaxy/blocks/ZGBlockBase.java#L146) is what throws the error

**Expected behavior**
To check the type before casting and not crash

**Minecraft and PC Information:**
 - Minecraft Version: `1.12.2`
 - Forge Version: `14.23.5.2860`
 - Mod Version: `2.0.45`
 - RAM allocated: `10 GB`

**Additional context**
Here is the [crash report](https://gist.github.com/TheComputerizer/333d537a4ac21abaaf1a1fb4b77f07dd). As you can see, this makes the mod unstable to play with [AoA3](https://www.curseforge.com/minecraft/mc-mods/advent-of-ascension-nevermine), although it may only be with [TickCentral](https://www.curseforge.com/minecraft/mc-mods/tickcentral) installed as well.

Personally I would recommend doing something like for your frostwalker test but any fix is a good one
```
boolean isLivingBase = (entityIn instanceof EntityLivingBase);
boolean hasFrostWalkerEnchantment = isLivingBase ? EnchantmentHelper.hasFrostWalkerEnchantment((EntityLivingBase) entityIn) : false;
```

**Comment by alphawolf918** [comment]
This has been fixed in the dev environment and will be applied when the new version is stable and released.
