### ISSUE TITLE
AvP Compat Issue

### ISSUE THREAD

**Issue by lartts** [alphawolf918/Zollern-Galaxy#95]
The game crashes when launching the game

Crash Log:
https://pastebin.com/RJ2EZ4qA

 - Minecraft Version: 1.12.2
 - Mod Version 2.0.45

**Comment by alphawolf918** [comment]
Biomes O Plenty was installed according to this log. Zollern Galaxy does not mix well with it. Mod compat issue. Contact their developers if you wish to use both.
